import Phaser from "phaser";
import isMobileOrTablet from "./Utils/isMobileOrTablet";

export default class Preloader extends Phaser.Scene {
  constructor() {
    super("preloader");
    this.progressBar = null;
  }

  preload() {
    const screenWidth = this.cameras.main.width;
    const screenHeight = this.cameras.main.height;

    this.progressBar = this.add.graphics();

    this.load.on(
      "progress",
      (value) => {
        this.progressBar.clear();
        this.progressBar.fillStyle(0xffffff, 1);
        this.progressBar.fillRect(0, screenHeight / 2, screenWidth * value, 30);
      },
      this
    );

    this.load.on("complete", () => this.progressBar.destroy(), this);

    this.load.image("tiles", "tiles/Asset_Atlas_01.png");
    // generated by https://www.mapeditor.org/
    this.load.tilemapTiledJSON("map", "tiles/3rivers.json");

    // generated by https://free-tex-packer.com/app/
    this.load.atlas("splash", "sprites/splash.png", "sprites/splash.json");
    this.load.atlas("mai", "sprites/mai.png", "sprites/mai.json");
    this.load.atlas("trees", "sprites/trees.png", "sprites/trees.json");
    this.load.atlas("sprites", "sprites/sprites.png", "sprites/sprites.json");

    if (isMobileOrTablet)
      this.load.plugin(
        "rexvirtualjoystickplugin",
        "plugins/rexvirtualjoystickplugin.min.js",
        true
      );

    // generated by https://snowb.org/
    this.load.bitmapFont('FreePixel-16', 'fonts/FreePixel-16.png', 'fonts/FreePixel-16.xml');
    this.load.bitmapFont('FreePixelStrokeShadow-16', 'fonts/FreePixelStrokeShadow-16.png', 'fonts/FreePixelStrokeShadow-16.xml');
  }

  create() {
    this.scene.start("game");
  }
}
